### PR TITLE
Use Rpch provider

### PR DESCRIPTION
**Pull request by ausias-armesto**
Use Rpch provider to decommission secondary server

### CODE REVIEW

**Review by tolbrino — CHANGES_REQUESTED** [review]
Actually, we should revert the Rust changes in this repo, since the currently deployed provider proxy is the one still using JS since that seemed to be faster.

Also is that provider able to handle the load?

**Review by Teebor-Choka — APPROVED** [review]

**Comment by Teebor-Choka** [comment]
Or do what @tolbrino suggests. 🍻

**Comment by ausias-armesto** [comment]
> Actually, we should revert the Rust changes in this repo, since the currently deployed provider proxy is the one still using JS since that seemed to be faster.
> 
> Also is that provider able to handle the load?

So you mean that I revert this PR https://github.com/hoprnet/provider-proxy/pull/13 and then change the URL?

**Comment by ausias-armesto** [comment]
Will be implemented in the Typescript code

**Pull request closed without merging**
